version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: myTaskDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5438:5432
    volumes:
      - ./data:/var/lib/postgresql/data